config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "public_recipes#index"
  
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  
  resources :foods, only: [:index, :create, :new, :show, :destroy]
  resources :recipes, except: :edit do 
    resources :recipe_foods, only: [:new, :create, :destroy]
    member do
      patch 'toggle_public'
    end
  end
  
  resources :public_recipes, only: [:index]
  resources :general_shopping_lists, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0.0 }

  def name_with_measurement_unit
    "#{name} (#{measurement_unit})"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes
  validates :name, presence: true, length: { minimun: 2, maximun: 50 }, allow_blank: false
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :description, presence: true, allow_blank: false
  validates :public, inclusion: { in: [true, false] }

  # prearation time:
  def preparation_time_minutes
    minutes = preparation_time % 60
    minutes.to_i
  end

  def preparation_time_hours
    hours = preparation_time / 60
    hours.to_i
  end

  # cooking time:
  def cooking_time_minutes
    minutes = cooking_time % 60
    minutes.to_i
  end

  def cooking_time_hours
    hours = cooking_time / 60
    hours.to_i
  end

  # total
  def total_time_minutes
    total = preparation_time + cooking_time
    minutes = total % 60
    minutes.to_i
  end

  def total_time_hours
    total = preparation_time + cooking_time
    hours = total / 60
    hours.to_i
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }

  def total_price
    food.price * quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods
  has_many :recipe_foods, through: :recipes
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = current_user.foods.includes(:user)
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)
    if @food.save
      redirect_to foods_path, notice: 'food created successfully'
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'food deleted successfully'
    else
      redirect_to foods_path, notice: 'failed to delete food'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  def index
    @recipe_foods = current_user.recipe_foods.group(:food_id).sum(:quantity)
    @foods = current_user.foods
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_foods_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'New ingredient added'
    else
      redirect_to new_recipe_recipe_food_path(@recipe.id)
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy!

    redirect_to recipe_path(@recipe.id), notice: 'Ingredient successfully deleted'
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes.includes(:user)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.includes(recipe_foods: [:food]).find(params[:id])
    @preparation_time_minutes = @recipe.preparation_time_minutes
    @preparation_time_hours = @recipe.preparation_time_hours
    @cooking_time_minutes = @recipe.cooking_time_minutes
    @cooking_time_hours = @recipe.cooking_time_hours
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    @recipe.preparation_time = calculate_minutes(params[:recipe][:preparation_time_hr],
                                                 params[:recipe][:preparation_time_min])
    @recipe.cooking_time = calculate_minutes(params[:recipe][:cooking_time_hr], params[:recipe][:cooking_time_min])

    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    render json: { public: @recipe.public }
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe successfully deleted'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :public)
  end

  def calculate_minutes(hours, minutes)
    (hours.to_i * 60) + minutes.to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_shopping_lists_helper.rb
module GeneralShoppingListsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/foods/index.html.erb
<h1 class=" text-center text-4xl">Food</h1>
   <div class="flex justify-center py-3">
   <div class='w-1/2'>
    <%= link_to "Add food", '/foods/new', class: "inline-block float-right 
 p-2  mb-1 bg-blue-500 text-white px-4 py-2 rounded-3xl cursor-pointer hover:bg-blue-400"%>
     <table class = "table">
        <thead>
        <tr>
            <th class='p-3'>Food</th>
            <th class='p-3'>measurement unit</th>
            <th class='p-3'>Unit price</th>
            <th class='p-3'>Action</th>
        </tr>
        </thead>
        <tbody>
    <% unless @foods.empty?%>
    
      <% @foods.each do|food| %>
        <tr>
            <td class="p-2"><%= food.name%></td>
            <td class="p-2"><%= food.measurement_unit%></td>
            <td class="p-2">$<%= food.price%></td>
            <td class="p-2"><%= button_to 'Delete', food_path(id: food.id), method: :delete,  class: 'border px-3 py-1 text-white bg-red-500 rounded-lg hover:scale-105 transition-all float-right' %></td>
            </tr>
       <%end%>  
        <% else %>
      <tr>
        <td colspan="4">No food items available.</td>
      </tr>
    <% end %>
    </tbody>   
    </table>
</div>

app/views/foods/new.html.erb
   <h1 class="my-5 font-bold text-center">Add New Food</h1>
   <div class="flex justify-center py-3">
        <%=form_with model: @food, url: foods_path, local: true do |form| %>
          <div class="mb-1">
            <%= form.text_field :name,class: "w-96", placeholder: "Enter food name"%>
            </div>
          <div class="mb-1">
            <%= form.text_field :measurement_unit,class: "w-96", placeholder: "Enter measurement unit (ex:grams)"%>
            </div>  
          <div class="mb-1">
            <%= form.text_field :price,class: "w-96", placeholder: "Enter price (ex:$1.5)"%>
            </div>
           <div class="mb-1">
            <%= form.number_field :quantity, class: "w-96", placeholder: "Enter quantity"%>
            </div>       
             <div class="flex justify-center col-span-2 mt-3">
            <%= form.submit "Create food", class: "bg-blue-500 text-white px-4 py-2 rounded-3xl cursor-pointer hover:bg-blue-400"%>
            </div>
         <% end %>
        </div>

app/views/general_shopping_lists/index.html.erb
<h1 class=" text-center text-4xl">Food</h1>
   <div class="flex justify-center py-3">
      <div class='w-1/2'>
    <%@all_item = 0%>
    <%@all_value = 0%>
    <%@foods.each do|food|%>
       <% if @recipe_foods.key?(food.id)%>
          <%quantity_calc = @recipe_foods[food.id] - food.quantity %>
          <%if quantity_calc > 0%>
             <%@all_item += quantity_calc%>
             <%@all_value += quantity_calc * food.price %>
         <%end%>
         <%end%>
        <%end%> 
     <div>
        <p>Amount of food to buy: <%= @all_item%></p>
        <p>Total value of food needed : $ <span><%= @all_value%> </span></p>
        <div>
   <table>
      <thead>
        <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
            <% @foods.each do |food|%>
               <% if @recipe_foods.key?(food.id)%>
                 <%quantity_calc = @recipe_foods[food.id] - food.quantity %>
                  <%if quantity_calc > 0%>
                    <tr>
                        <td><%=food.name%></td>
                        <td><%=quantity_calc%></td>
                        <td><%=quantity_calc * food.price%></td>

                 </tr>  
                 <%end%>
                 <%end%>
                 <%end%>         
        </tbody>
    </table>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render 'shared/navmenu' %>
    <main class="container mx-auto"">
       <p class="notice flex flex-col items-center p-4 mb-2 text-blue-800 rounded-lg dark:bg-gray-800 dark:text-blue-400" ><%= notice %></p>
       <p class="alert flex  flex-col items-center p-4 mb-2 text-red-800 rounded-lg dark:bg-gray-800 dark:text-red-400" ><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h1 class="text-center text-4xl"> Public Recipes </h1>
<% if @recipes.length != 0 %>
<div class="flex flex-wrap gap-2 justify-center p-6 ">
<%  @recipes.each do |rec|%>
<%= render 'shared/pub_recipe_card', recipe: rec %>
<% end %>
<% else %>
<h1 class="font-extrabold lg:text-4xl md:text-3xl mt-5 text-2xl text-center text-red-800">There are no public recipes to show</h1>
<% end %>

</div>

app/views/recipe_foods/new.html.erb
<div class="flex justify-center items-center flex-col">
    <div class="">
        <h2 class="text-xl ">Add new ingredient to: </h2>
        <h3 class="text-center text-2xl font-bold"><%= @recipe.name %></h3>
        <div class=" mt-5  p-5">
            <%= form_with model: [@recipe, @recipe_food] do |f|%>
                <div class="form-field mb-5">
                    <%= f.collection_select :food_id, current_user.foods.order(:name), :id, :name_with_measurement_unit ,{prompt: "Choose ingredients"}, {value: " "} %>
                </div>

                <div class="form-field mb-5">
                        <%= f.number_field :quantity, placeholder: 'Quantity', required: true, step: '0.01'%>
                </div>

                <div class="form-field mb-5">
                    <%= f.submit "Add new ingredient" , class: 'border bg-blue-500 px-3 py-1 text-white rounded-md w-fill'%>
                </div>
            <% end %>

        </div>
    </div>
</section>

app/views/recipes/index.html.erb
<h1 class="text-center text-4xl"> My Recipes </h1>
<div class="flex flex-col flex-wrap gap-2 items-center bg-primary p-6">
  <% if @recipes.empty?%>
    <h2 class="mb-5">You don't have recipes yet</h2>
  <% else%>
    <% @recipes.each do |rec| %>
        <%= render "shared/recipe_card", recipe: rec %>
    <% end %>
  <% end %>
  <%= link_to "Add Recipe", new_recipe_path, class: 'bg-blue-500 text-white px-4 py-2 rounded-3xl cursor-pointer hover:bg-blue-400'%>

app/views/recipes/new.html.erb
<h1 class="my-5 font-bold text-center">Add New Recipe</h1>
   <div class="flex justify-center py-3">
  <%= form_with model: @recipe, url: recipes_path ,class: "grid gap-1" do |form| %>
      <%= form.label :name, "Recipe name: " %>
      <%= form.text_field :name, class: "border border-slate-200", required: true %>
      <%= form.label :description, "Recipe description: " %>
      <%= form.text_area :description, rows:5, class: "border border-slate-200", required: true %>
      <%= form.label :preparation_time, "Preparation time: " %>
      <div class="flex gap-2">
        <%= form.number_field :preparation_time_hr, placeholder: 0 , class: "border border-slate-200 w-1/5 text-center", required: true%>
        <%= form.label :preparation_time_hr, "hr",class: "w-1/12" %>
        <%= form.number_field :preparation_time_min, placeholder: 0 , in: 0..60, class: "border border-slate-200 w-1/5 text-center", required: true%>
        <%= form.label :preparation_time_min, "min",class: "w-1/12" %>      
      </div>
      <%= form.label :cooking_time, "Cooking time: " %>
      <div class="flex gap-2">
        <%= form.number_field :cooking_time_hr, placeholder: 0, class: "border border-slate-200 w-1/5 text-center", required: true%>
        <%= form.label :cooking_time_hr, "hr",class: "w-1/12" %>
        <%= form.number_field :cooking_time_min, placeholder: 0, in: 0..60, class: "border border-slate-200 w-1/5 text-center", required: true%>
        <%= form.label :cooking_time_min, "min",class: "w-1/12" %>      
      </div>

      <div class="flex justify-center col-span-2 gap-3 mt-3">
        <%= form.check_box :public %>
        <%= form.label :public, "Made recipe public" %>
      </div>
      <div class="flex justify-center col-span-2 mt-3">
          <%= form.submit "Add new recipe", class:"bg-blue-500 text-white px-4 py-2 rounded-3xl cursor-pointer hover:bg-blue-400" %>
      </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<section class="flex justify-center p-3">
  <div class="flex flex-col items-center w-full gap-5">
    <% if current_user == @recipe.user %>
        <%= form_with model: @recipe, method: :patch, class: "public-form", data: { url: toggle_public_recipe_path(@recipe), recipe_id: @recipe.id } do |form| %>
        <div class="mt-3 flex items-center gap-2">
          <label class="switch">
            <input type="checkbox" <%= 'checked' if @recipe.public %> onchange="togglePublic(this)">
            <span class="slider"></span>
          </label>
          <%= form.label :public, "Public" %>
        </div>
      <% end %>
    <% end %>
    <div class="relative flex flex-col items-center p-4 border-2 border-gray-100 sm:px-24 rounded-2xl bg-clip-padding backdrop-filter backdrop-blur-3xl bg-gray-50">
      <div class="flex flex-col items-center gap-3">
        <h1 class="text-4xl font-bold text-center text-clamp-2">
          <%= @recipe.name %>
        </h1>
        <p class="text-sm text-center text-slate-400">
          by <%= @recipe.user.name %>
        </p>
        <p class="text-center text-slate-500 max-w-[35ch]">
          <%= @recipe.description %>
        </p>
        <div class="flex w-full justify-evenly">
          <div class="flex flex-col gap-2 py-3 text-center mr-4">
            <h2 class="capitalize">Preparation time</h2>
            <div class="flex text-sm justify-evenly">
              <% if @preparation_time_hours > 0 %>
                <%= "#{@preparation_time_hours} hr" %>
              <% end %>
              <% if @preparation_time_minutes > 0 %>
                <%= "#{@preparation_time_minutes} min" %>
              <% end %>
            </div>
          </div>
          <div class="flex flex-col gap-2 py-3 text-center mr-4">
            <h2 class="capitalize">Cooking time</h2>
            <div class="flex text-sm justify-evenly">
              <% if @cooking_time_hours > 0 %>
                <%= "#{@cooking_time_hours} hr" %>
              <% end %>
              <% if @cooking_time_minutes > 0 %>
                <%= "#{@cooking_time_minutes} min" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="flex justify-between w-1/2">
       <div>
        <%= link_to "Generate shopping list" , general_shopping_lists_path , class: 'border bg-blue-500 px-3 py-1 text-white rounded-md' %>
      </div>
      <div>
        <%= link_to "Add ingredient",  new_recipe_recipe_food_path(@recipe.id), class: 'border bg-blue-500 px-3 py-1 text-white rounded-md' %>
      </div>
    </div>
    <div class='w-1/2'>
          <table class="border">
            <thead class="border">
                <tr>
                <th class="p-2">Food</th>
                <th class="p-2">Quantity</th>
                <th class="p-2">Value</th>
                <th class="p-2">Action</th>
                </tr>
            </thead>
  <tbody >
<% unless @recipe.recipe_foods.empty?%>
    <tr >
    <% @recipe.recipe_foods.each do |recipe_food|%>
      <td class="p-2"><%= recipe_food.food.name %></td>
      <td class="p-2"><%= recipe_food.quantity %></td>
      <td class="p-2"><%= recipe_food.total_price %></td>
      <td class="p-2">
        <%= button_to 'Delete', recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id ), method: :delete, class: 'border px-3 py-1 text-white bg-red-500 rounded-lg hover:scale-105 transition-all float-right' %>
      </td>

    </tr>
     <%end%>  
       <% else %>
      <tr>
        <td colspan="4">No items available.</td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</section>

<script>
 function togglePublic(checkbox) {
    var form = checkbox.closest("form");
    var recipeId = form.dataset.recipeId;
    var url = form.dataset.url;

    var formData = new FormData();
    formData.append("recipe_id", recipeId);

    fetch(url, {
      method: "PATCH",
      body: formData,
      headers: {
        "X-CSRF-Token": document.querySelector("meta[name=csrf-token]").content
      }
    })
      .then(response => response.json())
      .then(data => {
        // Handle the response from the server if needed
        console.log(data);
      })
      .catch(error => {
        // Handle errors if any
        console.error(error);
      });
  }
</script>

app/views/shared/_navmenu.html.erb
<nav class="bg-grey border-gray-200 dark:bg-gray-900">
  <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl px-4 md:px-6 py-2.5">
    <%= link_to 'Recipe App', root_path , class:"self-center text-xl font-semibold whitespace-nowrap dark:text-white" %>
    <div class="flex items-center">
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, class: 'text-blue-600' %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path , class: 'text-blue-600' %>
      <% end %>
    </div>
  </div>
</nav>
<% if user_signed_in? %>
  <nav class="bg-gray-50 dark:bg-gray-700">
    <div class="max-w-screen-xl px-4 py-3 mx-auto md:px-6">
      <div class="flex items-center">
        <ul class="flex flex-row mt-0 mr-6 space-x-8 text-sm font-medium">
          <li>
            <%= link_to 'Public Recipes', public_recipes_path , class: 'text-gray-900 dark:text-white hover:underline' %>
          </li>
          <li>
            <%= link_to 'Foods', foods_path , class: 'text-gray-900 dark:text-white hover:underline' %>
          </li>
          <li>
            <%= link_to 'Recipes', recipes_path , class: 'text-gray-900 dark:text-white hover:underline' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/shared/_pub_recipe_card.html.erb
<div class="border w-1/2 border-current rounded-3xl p-6 m-5 bg-gray-50">
    <div class="flex justify-between">
      <div class="text-xl font-bold text-gray-900 mb-2">
        <h3 class='text-2xl hover:scale-105 hover:opacity-50'>
          <%= link_to recipe.name, recipe_path(id: recipe.id) %>
        </h3>
        <h5 class="text-base text-zinc-600 font-regular">By: <%= recipe.user.name %>
        </h5>
      </div>
      <div>
        <h5 class="mt-3" style="margin-right: 20px">Total foods: <%= recipe.recipe_foods.length %> </h5>
        <% sum = 0 %>
        <h5 style="margin-right: 120px">Total price : $ <% recipe.recipe_foods.each do |food| %>
            <% sum += food.food.price %>
          <% end %>
          <%= sum %></h5>
      </div>
    </div>
    <div class="">
      <div class="col-span-12 sm:col-span-8">
        <span class='text-base text-zinc-600 font-regular'>Description:</span>
        <p class="card-text">
          <%= recipe.description %>
        </p>
      </div>
      <div class="d-flex justify-content-end">
        <p class="opacity-50 text-right"><%= time_ago_in_words(recipe[:created_at]) %></p>
      </div>
    </div>
  </div>

app/views/shared/_recipe_card.html.erb
 <div class="border w-1/2 border-current rounded-3xl p-3 m-5 bg-gray-50"">
    <a href="<%= recipe_path(recipe) %>" class="rounded-xl flex items-center p-5 hover:bg-slate-300 transition-all">
      <div>
        <h2 class="capitalize font-bold text-2xl text-left">
          <%= recipe.name %>
        </h2>
        <div class="line-clamp-2 text-slate-500">
          <%= recipe.description %>
        </div>
      </div>
    </a>

    <div class="text-right">
      <%= button_to 'Delete', recipe_path(id: recipe.id), method: :delete, class: 'border px-3 py-1 text-white bg-red-500 my-5 rounded-lg hover:scale-105 transition-all' %>
    </div>
  </div>